### ISSUE TITLE
MySQL - Node.js 연동 프로토타입 개발

### ISSUE THREAD

**Issue by asd123fdssal** [asd123fdssal/sdmc-node.js-server#6]
## Description
MySQL과 Node.js를 연동하여 DB에 존재하는 테이블을 조회하는 프로토타입 제작

## Todo
- [x] 로컬 DB 연동 확인
- [x] 웹서버 DB 연동 확인

**Comment by asd123fdssal** [comment]
Description
보안을 위하여 DB Connection 정보는 형상관리에 포함하지 않는다.

Todo
- [ ] .gitignore에 DB정보가 담긴 .js파일은 제외한다.
